### ISSUE TITLE
compute node's root partition needs to be bigger

### ISSUE THREAD

**Issue by A1ve5** [CSC-IT-Center-for-Science/ansible-role-pxe_config#9]
/ capacity isn't enough. It should be the one that grows.
Consider /local optional and with a fixed size
https://github.com/CSC-IT-Center-for-Science/fgci-ansible/blob/master/examples/group_vars/compute/compute.example#L85

**Comment by A1ve5** [comment]
@jabl What are the implications for you to make an optional /local with a fixed size. Which size is OK? Size could also be a variable.
Right now 50GB for / is too short and not every site will use /local.

**Comment by jabl** [comment]
We're happy with the current partitioning, where we have a partition "/l" which fills the rest of the disk, and then slurm is setup such that /tmp and /var/tmp are per-job specific, bind-mounted to that partition and deleted at the end of the job. As we have jobs which use a huge amount of local scratch space, we'd like to keep /l as big as possible. And we'd like to keep /l a separate partition, so that jobs which accidentally (?) fill the entire disk won't fill /. 50G for / is also fine for us, currently on our compute nodes only 6% is used.

That being said, since the partitioning comes from group_vars each site can override the defaults with whatever they like?

**Comment by A1ve5** [comment]
Yes, I'm changing the example file with a warning that each site is responsible to tune their computes partition layout. 
Some site was complaining that / was full... and there are sites with 4TB compute nodes that don't use /local (/l) part so I'll suggest every one to make their own layout with some minimal requirements.
Thanks for answering.
